name: AWS CodeDeploy Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Configure AWS credentials
        run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set default.region us-east-1

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Create CodeDeploy application
        run: aws deploy create-application --application-name my-app-2 --compute-platform Server

      - name: Create CodeDeploy deployment group
        run: aws deploy create-deployment-group --application-name my-app-2 --deployment-group-name deploy-gr --deployment-config-name CodeDeployDefault.OneAtATime --ec2-tag-filters Key=Name,Value=my-instance,Type=KEY_AND_VALUE

      - name: Create CodeDeploy deployment
        run: aws deploy create-deployment --application-name my-app-2 --deployment-group-name deploy-gr --s3-location bucket=web-my-bucket,bundleType=zip,key=my-app.zip
