name: CI/CD for AWS Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create CodeDeploy application
        run: aws deploy create-application --application-name my-app-2

      - name: Create CodeDeploy deployment group
        run: aws deploy create-deployment-group --application-name my-app-2 --deployment-group-name deploy-gr --deployment-config-name CodeDeployDefault.OneAtATime

      - name: Create deployment
        run: aws deploy create-deployment --application-name my-application --deployment-group-name deploy-gr --s3-location bucket=web-my-bucket,key=my-app.zip,bundleType=zip

      - name: Wait for deployment to complete
        run: aws deploy wait deployment-successful --deployment-id ${{ steps.create_deployment.outputs.deployment-id }}
